"""Generates docs/RULES.md from the live calibration + scoring, so the evidence can never drift from the code.
Run:  python -m app.report"""
from collections import Counter
from pathlib import Path

from .calibration import calibrate
from .features import add_derived, load_raw
from .customrules import RuleConfig
from .rules import LEVEL_W, RULE_META, catalog, evaluate
from .scoring import BANDS, baseline_anomaly, level_for, score_case

OUT = Path(__file__).resolve().parent.parent / "docs" / "RULES.md"
LABEL = {"weekly_visit_frequency": "Visits / week", "member_provider_distance_miles": "Distance (miles)",
         "prior_claims_last_12mo": "Prior claims (12 mo)", "weekend_billing_ratio": "Weekend billing ratio",
         "amount_vs_peer_avg_pct": "Amount vs peer avg (%)", "round_dollar_billing_ratio": "Round-dollar ratio",
         "implied_weekly_travel_miles": "Implied weekly travel miles (derived)"}


def cut_gap(scores, cut, name):
    below = max((x for x in scores if x < cut), default=None)
    above = min((x for x in scores if x >= cut), default=None)
    return f"{name} cut {cut}: nearest scores {below} | {above}"


def build():
    cal, _ = calibrate()
    rows = add_derived(load_raw())
    scored, fire = [], Counter()
    for r in rows:
        f = evaluate(r, cal, RuleConfig.empty())
        s, rs, _ = score_case(f, baseline_anomaly(r, rows))
        scored.append((s, r["case_id"], f))
        fire.update(x["rule_id"] for x in f)
    scores = sorted(s for s, _, _ in scored)
    lvl = Counter(level_for(s) for s, _, _ in scored)
    L = ["# Rule evidence (auto-generated by `python -m app.report`)", "",
         "Every threshold below is computed from the 50-case portfolio, not chosen by hand.", "",
         "## Method", "",
         "1. **Natural breaks.** For each continuous signal the sorted values are split into 3 groups (baseline / elevated / extreme) "
         "by minimising within-group variance (Jenks, k=3, exact DP). The threshold is the midpoint of the empty gap between adjacent groups, "
         "so it sits where the real distribution has no cases.",
         "2. **Rule levels.** Crossing the *elevated* break = MEDIUM, crossing the *extreme* break = HIGH. Binary flags are HIGH except "
         "`recent_policy_change_flag` (LOW: 12/50 and weak on its own).",
         "3. **Domains.** Signals are grouped into Billing / Utilization / Geography / Relationship / Timing. In this data the signals co-move "
         "(the 8 worst cases trip *everything*), so summing rules would double-count. The score takes the strongest rule per domain and combines "
         "domains with noisy-OR: `score = 1 - prod(1 - w_domain)`, weights " + ", ".join(f"{k}={v}" for k, v in LEVEL_W.items()) + ".",
         "4. **Baseline anomaly (0-10).** Mean percentile rank of the continuous signals, blended in so clean cases still get a stable order.",
         "5. **Bands.** " + ", ".join(f">={c} {n}" for c, n in BANDS) + ". Each cut falls inside an empty stretch of the scored portfolio "
         "(no case scores between the two neighbours): " + "; ".join(cut_gap(scores, c, n) for c, n in BANDS[:-1]) + ".", "",
         "## Signal calibration", "",
         "| Signal | Baseline (min-max, n) | Elevated (min-max, n) | Extreme (min-max, n) | MEDIUM at | HIGH at |", "|---|---|---|---|---|---|"]
    for k, v in cal["signals"].items():
        g = v["groups"]
        fmt = lambda x: f"{x[0]}-{x[1]} ({x[2]})"
        L.append(f"| {LABEL[k]} | {fmt(g['baseline'])} | {fmt(g['elevated'])} | {fmt(g['extreme'])} | >= {v['elevated_threshold']} | >= {v['extreme_threshold']} |")
    L += ["", f"Claim amount (log-scale robust z, median/MAD): outlier threshold z >= {cal['log_amount_robust_z']['outlier_threshold']}; "
          f"portfolio median ${cal['amount']['median']:,.0f}, p75 ${cal['amount']['p75']:,.0f}, p90 ${cal['amount']['p90']:,.0f}.", "",
          "Binary flag base rates: " + ", ".join(f"`{k}` {v['count']}/{cal['n_cases']}" for k, v in cal["binary"].items()) + ".", "",
          "## Rule catalog", "", "| ID | Rule | Domain | Logic | Fires on |", "|---|---|---|---|---|"]
    for r in catalog(cal, RuleConfig.empty()):
        L.append(f"| {r['rule_id']} | {r['name']} | {r['domain']} | {r['logic']} | {fire.get(r['rule_id'], 0)}/{cal['n_cases']} |")
    L += ["", "Derived-feature rationale:", "",
          "- **R11 implied weekly travel miles** = visits/wk x distance x 2. Baseline cases stay below ~1.3k; the 8 worst cases sit at 2.3k-7.5k "
          "(a member or provider covering thousands of miles a week is physically implausible).",
          "- **R13 convergence** counts domains tripped at >= MEDIUM. Because signals co-move, independent-domain convergence is the strongest evidence.",
          "- **R14 silent drift.** Of the zero-flag cases, 30 trip none of the 7 continuous signals and 3 (C1026, C1040, C1042) trip five; nothing in between. "
          "A flag-count model scores those 3 as clean. Threshold = 3 (midpoint of the empty gap).",
          "- **R15 claim-number reuse.** `LTC-2034786` appears on C1001 (benign profile) and C1031 (critical profile) -- a data-integrity lead that no per-row rule can see.",
          "- Not derivable (documented gap): days since policy change (only a 0/1 flag), provider identity, member identity, diagnosis.", "",
          "## Resulting score distribution", "", "| Level | Cases |", "|---|---|"]
    L += [f"| {l} | {lvl.get(l, 0)} |" for l in ("CRITICAL", "HIGH", "MEDIUM", "LOW")]
    L += ["", f"Cases with score < 10: {sum(1 for s, _, _ in scored if s < 10)} (all have zero rules fired).", "",
          "## Caveats", "",
          "- Thresholds are calibrated to a 50-row synthetic sample. There are **no fraud labels**, so precision/recall cannot be claimed; "
          "in production the weights and breaks should be re-fit against confirmed outcomes.",
          "- The 3-tier structure (8 / ~9 / 33) is very clean because the data is synthetic; real portfolios are continuous, which is why the LLM judge "
          "and human review sit on top of the rules rather than replacing them."]
    OUT.parent.mkdir(exist_ok=True)
    OUT.write_text("\n".join(L) + "\n")
    return OUT


if __name__ == "__main__":
    print("wrote", build())
